package com.lu.xmpp.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_LOG".
 */
public class ChatLog {

    private long id;
    /** Not-null value. */
    private String from;
    private java.util.Date time;
    private Boolean isRead;
    private String body;

    public ChatLog() {
    }

    public ChatLog(long id) {
        this.id = id;
    }

    public ChatLog(long id, String from, java.util.Date time, Boolean isRead, String body) {
        this.id = id;
        this.from = from;
        this.time = time;
        this.isRead = isRead;
        this.body = body;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFrom() {
        return from;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFrom(String from) {
        this.from = from;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

}
